# Generated by Django 4.0.2 on 2022-02-09 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('competition_id', 'user_id')},
        ),
    ]
